# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='asignado_por',
        ),
        migrations.RemoveField(
            model_name='item',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
