# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
