# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=1)),
                ('peso', models.FloatField(max_length=5)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=12)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
