# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signos_Vitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tension_arterial', models.CharField(max_length=10)),
                ('frecuencia_cardiaca', models.CharField(max_length=10)),
                ('frecuencia_respiratoria', models.CharField(max_length=10)),
                ('temperatura', models.CharField(max_length=10)),
                ('notas', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
