# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20161129_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=10)),
                ('dosis', models.CharField(max_length=40)),
                ('frecuencia', models.CharField(max_length=10)),
                ('via', models.CharField(max_length=10)),
                ('nota', models.CharField(max_length=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
