# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otras_Ordenes_Terapeuticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dieta', models.CharField(max_length=60)),
                ('actividad_fisica', models.CharField(max_length=30)),
                ('curas', models.CharField(max_length=30)),
                ('oxigeno', models.CharField(max_length=20)),
                ('fisioterapia_respiratoria', models.CharField(max_length=20)),
                ('sondas_drenajes', models.CharField(max_length=20)),
                ('estudios_lab_diagnostico', models.CharField(max_length=60)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
