# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_otras_ordenes_terapeuticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='frecuencia',
            field=models.CharField(max_length=30),
        ),
    ]
